version: '3.7'
services:
  node8x:
    build: 
      context: .
      target: 'node8x'
    command: sh /usr/app/entrypoint.sh
  node9x:
    build: 
      context: .
      target: 'node9x'
    command: sh /usr/app/entrypoint.sh
  node10x:
    build: 
      context: .
      target: 'node10x'
    command: sh /usr/app/entrypoint.sh
  node11x:
    build: 
      context: .
      target: 'node11x'
    command: sh /usr/app/entrypoint.sh
  node12x:
    build: 
      context: .
      target: 'node12x'
    command: sh /usr/app/entrypoint.sh
  node13x:
    build: 
      context: .
      target: 'node13x'
    command: sh /usr/app/entrypoint.sh
  docs:
    build: 
      context: .
      target: 'node11x'
    command: sh /usr/app/entrypoint-docs.sh
    volumes:
      - ./:/usr/app
 
